# Generated by Django 5.2.11 on 2026-02-08 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi-newspaper', max_length=50)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
            },
        ),
        migrations.CreateModel(
            name='AgriNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('news_type', models.CharField(choices=[('government', 'Government Policy'), ('market', 'Market Update'), ('weather', 'Weather Alert'), ('technology', 'Agricultural Technology'), ('event', 'Event/Training'), ('advertisement', 'Advertisement')], max_length=20)),
                ('content', models.TextField()),
                ('summary', models.TextField(help_text='Brief summary for preview')),
                ('source', models.CharField(help_text='e.g., Ministry of Agriculture', max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark as urgent alert')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscategory')),
            ],
            options={
                'verbose_name': 'Agricultural News',
                'verbose_name_plural': 'Agricultural News',
                'ordering': ['-published_at'],
            },
        ),
    ]
