# Generated by Django 5.2.11 on 2026-06-16 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_agrienews_status_source_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrinews',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newscategory'),
        ),
    ]
