# Generated by Django 5.2.11 on 2026-02-07 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Vegetables, Fruits)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('image', models.ImageField(blank=True, help_text='Category icon/image', null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name (e.g., Fresh Matooke)', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the product')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit in UGX', max_digits=10)),
                ('quantity', models.IntegerField(help_text='Available quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('bags', 'Bags'), ('bunches', 'Bunches'), ('pieces', 'Pieces'), ('liters', 'Liters'), ('tons', 'Tons')], default='kg', max_length=20)),
                ('location', models.CharField(help_text='Where product is located (district/city)', max_length=100)),
                ('image', models.ImageField(help_text='Main product image', upload_to='products/')),
                ('image2', models.ImageField(blank=True, help_text='Additional image', null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, help_text='Additional image', null=True, upload_to='products/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.category')),
                ('farmer', models.ForeignKey(help_text='Farmer who listed this product', limit_choices_to={'user_type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
