# Generated by Django 5.2.11 on 2026-02-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, help_text='When was this harvested', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark as urgent sale (reduces post-harvest losses)'),
        ),
        migrations.AddField(
            model_name='product',
            name='urgent_discount',
            field=models.IntegerField(default=0, help_text='Discount percentage for urgent sales (0-50%)'),
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name (e.g., Maize, Coffee, Matooke)', max_length=200)),
                ('market_location', models.CharField(help_text='Market location (e.g., Owino Market, Nakasero)', max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Minimum price in UGX', max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, help_text='Maximum price in UGX', max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=2, help_text='Average market price in UGX', max_digits=10)),
                ('unit', models.CharField(default='kg', help_text='Unit of measurement', max_length=20)),
                ('date_recorded', models.DateField(auto_now_add=True, help_text='Date when price was recorded')),
                ('source', models.CharField(default='Market Survey', help_text='Source of price information', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='marketplace.category')),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
