# Generated by Django 5.2.11 on 2026-02-08 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_harvest_date_product_is_urgent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdsourcedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('buyer_type', models.CharField(choices=[('middleman', 'Middleman'), ('direct_consumer', 'Direct Consumer'), ('business', 'Business/Restaurant'), ('market', 'Market Vendor')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('market_name', models.CharField(blank=True, max_length=200)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Additional context')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crowdsourced Price',
                'verbose_name_plural': 'Crowdsourced Prices',
                'ordering': ['-date_reported'],
            },
        ),
    ]
