# Generated by Django 5.2.11 on 2026-02-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_crowdsourcedprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product/commodity name', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in UGX', max_digits=10)),
                ('unit', models.CharField(default='kg', help_text='Unit of measurement', max_length=20)),
                ('market_location', models.CharField(help_text='Market or region', max_length=100)),
                ('source', models.CharField(choices=[('wfp', 'World Food Programme'), ('fao', 'FAO GIEWS'), ('ubos', 'Uganda Bureau of Statistics'), ('other', 'Other')], default='wfp', help_text='Data source', max_length=20)),
                ('date_recorded', models.DateField(help_text='Date when price was recorded')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When we fetched this data')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this price is still current')),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('raw_data', models.JSONField(blank=True, help_text='Original API response for reference', null=True)),
            ],
            options={
                'verbose_name': 'External Market Price',
                'verbose_name_plural': 'External Market Prices',
                'ordering': ['-date_recorded', '-fetched_at'],
                'indexes': [models.Index(fields=['product_name', '-date_recorded'], name='marketplace_product_8f399e_idx'), models.Index(fields=['source', '-date_recorded'], name='marketplace_source_a10986_idx')],
            },
        ),
    ]
