# Generated by Django 5.2.11 on 2026-07-05 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('orders', '0002_deliveryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('offer', 'Price Offer'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('deal_done', 'Deal Finalised')], db_index=True, default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Proposed price per unit (UGX)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='offer_quantity',
            field=models.IntegerField(blank=True, help_text='Proposed quantity for this offer', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded by New Offer')], help_text='Lifecycle status of this offer message', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='NegotiatedDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.DecimalField(decimal_places=2, help_text='Agreed price per unit (UGX)', max_digits=10)),
                ('agreed_quantity', models.IntegerField(help_text='Agreed quantity')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('offer_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='chat.chatmessage')),
                ('order', models.OneToOneField(blank=True, help_text='The order created from this deal (null until buyer places order)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiated_deal', to='orders.order')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='chat.chatthread')),
            ],
            options={
                'verbose_name': 'Negotiated Deal',
                'verbose_name_plural': 'Negotiated Deals',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
