# Generated by Django 5.2.11 on 2026-02-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_farmerprofile_organic_certified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, help_text="User's district in Uganda", max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True, help_text="Track if this is user's first login for welcome message"),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, help_text="User's agricultural specialization", max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_size',
            field=models.DecimalField(decimal_places=2, help_text='Farm size in acres', max_digits=10),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='specialization',
            field=models.CharField(help_text='Primary farming specialization', max_length=200),
        ),
        migrations.AlterField(
            model_name='inputsupplierprofile',
            name='specialization',
            field=models.CharField(help_text='Type of agricultural inputs supplied', max_length=200),
        ),
    ]
