# Generated by Django 5.2.11 on 2026-02-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_district_user_first_login_user_specialization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inputsupplierprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='organic_certified',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='years_of_experience',
        ),
        migrations.RemoveField(
            model_name='inputsupplierprofile',
            name='total_orders',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='specialization',
            field=models.CharField(choices=[('Crop Farming', 'Crop Farming'), ('Livestock Farming', 'Livestock Farming'), ('Poultry Farming', 'Poultry Farming'), ('Fish Farming (Aquaculture)', 'Fish Farming (Aquaculture)'), ('Dairy Farming', 'Dairy Farming'), ('Horticulture', 'Horticulture'), ('Apiculture (Beekeeping)', 'Apiculture (Beekeeping)'), ('Mixed Farming', 'Mixed Farming'), ('Organic Farming', 'Organic Farming'), ('Agricultural Extension', 'Agricultural Extension'), ('Agribusiness', 'Agribusiness'), ('Agricultural Research', 'Agricultural Research'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='inputsupplierprofile',
            name='specialization',
            field=models.CharField(choices=[('Crop Farming', 'Crop Farming'), ('Livestock Farming', 'Livestock Farming'), ('Poultry Farming', 'Poultry Farming'), ('Fish Farming (Aquaculture)', 'Fish Farming (Aquaculture)'), ('Dairy Farming', 'Dairy Farming'), ('Horticulture', 'Horticulture'), ('Apiculture (Beekeeping)', 'Apiculture (Beekeeping)'), ('Mixed Farming', 'Mixed Farming'), ('Organic Farming', 'Organic Farming'), ('Agricultural Extension', 'Agricultural Extension'), ('Agribusiness', 'Agribusiness'), ('Agricultural Research', 'Agricultural Research'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('Central Region', [('Kampala', 'Kampala'), ('Wakiso', 'Wakiso'), ('Mpigi', 'Mpigi'), ('Mukono', 'Mukono'), ('Luwero', 'Luwero'), ('Nakasongola', 'Nakasongola'), ('Masaka', 'Masaka'), ('Rakai', 'Rakai'), ('Kalangala', 'Kalangala'), ('Lyantonde', 'Lyantonde'), ('Sembabule', 'Sembabule'), ('Bukomansimbi', 'Bukomansimbi')]), ('Eastern Region', [('Jinja', 'Jinja'), ('Iganga', 'Iganga'), ('Mayuge', 'Mayuge'), ('Bugiri', 'Bugiri'), ('Tororo', 'Tororo'), ('Busia', 'Busia'), ('Mbale', 'Mbale'), ('Bududa', 'Bududa'), ('Manafwa', 'Manafwa'), ('Sironko', 'Sironko'), ('Kapchorwa', 'Kapchorwa'), ('Kween', 'Kween'), ('Bukwo', 'Bukwo'), ('Soroti', 'Soroti'), ('Serere', 'Serere'), ('Kumi', 'Kumi'), ('Bukedea', 'Bukedea')]), ('Northern Region', [('Gulu', 'Gulu'), ('Kitgum', 'Kitgum'), ('Pader', 'Pader'), ('Agago', 'Agago'), ('Amuru', 'Amuru'), ('Nwoya', 'Nwoya'), ('Lamwo', 'Lamwo'), ('Lira', 'Lira'), ('Alebtong', 'Alebtong'), ('Apac', 'Apac'), ('Dokolo', 'Dokolo'), ('Oyam', 'Oyam'), ('Kole', 'Kole'), ('Otuke', 'Otuke'), ('Arua', 'Arua'), ('Koboko', 'Koboko'), ('Maracha', 'Maracha'), ('Yumbe', 'Yumbe'), ('Nebbi', 'Nebbi'), ('Zombo', 'Zombo'), ('Moyo', 'Moyo')]), ('Western Region', [('Mbarara', 'Mbarara'), ('Isingiro', 'Isingiro'), ('Kiruhura', 'Kiruhura'), ('Ntungamo', 'Ntungamo'), ('Kabale', 'Kabale'), ('Kisoro', 'Kisoro'), ('Rukungiri', 'Rukungiri'), ('Kanungu', 'Kanungu'), ('Kasese', 'Kasese'), ('Bundibugyo', 'Bundibugyo'), ('Kabarole', 'Kabarole'), ('Kyenjojo', 'Kyenjojo'), ('Bushenyi', 'Bushenyi'), ('Sheema', 'Sheema'), ('Mitooma', 'Mitooma'), ('Hoima', 'Hoima'), ('Masindi', 'Masindi'), ('Kiryandongo', 'Kiryandongo')])], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('Crop Farming', 'Crop Farming'), ('Livestock Farming', 'Livestock Farming'), ('Poultry Farming', 'Poultry Farming'), ('Fish Farming (Aquaculture)', 'Fish Farming (Aquaculture)'), ('Dairy Farming', 'Dairy Farming'), ('Horticulture', 'Horticulture'), ('Apiculture (Beekeeping)', 'Apiculture (Beekeeping)'), ('Mixed Farming', 'Mixed Farming'), ('Organic Farming', 'Organic Farming'), ('Agricultural Extension', 'Agricultural Extension'), ('Agribusiness', 'Agribusiness'), ('Agricultural Research', 'Agricultural Research'), ('Other', 'Other')], max_length=100),
        ),
    ]
