# Generated by Django 5.2.11 on 2026-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_farmerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('Central Region', [('Buikwe', 'Buikwe'), ('Bukomansimbi', 'Bukomansimbi'), ('Buvuma', 'Buvuma'), ('Gomba', 'Gomba'), ('Kalangala', 'Kalangala'), ('Kalungu', 'Kalungu'), ('Kampala', 'Kampala'), ('Kayunga', 'Kayunga'), ('Kiboga', 'Kiboga'), ('Kyankwanzi', 'Kyankwanzi'), ('Luweero', 'Luweero'), ('Lwengo', 'Lwengo'), ('Lyantonde', 'Lyantonde'), ('Masaka', 'Masaka'), ('Mityana', 'Mityana'), ('Mpigi', 'Mpigi'), ('Mubende', 'Mubende'), ('Mukono', 'Mukono'), ('Nakaseke', 'Nakaseke'), ('Nakasongola', 'Nakasongola'), ('Rakai', 'Rakai'), ('Sembabule', 'Sembabule'), ('Wakiso', 'Wakiso')]), ('Eastern Region', [('Amuria', 'Amuria'), ('Budaka', 'Budaka'), ('Bududa', 'Bududa'), ('Bugiri', 'Bugiri'), ('Bugweri', 'Bugweri'), ('Bukedea', 'Bukedea'), ('Bukwa', 'Bukwa'), ('Bulambuli', 'Bulambuli'), ('Busia', 'Busia'), ('Buyende', 'Buyende'), ('Iganga', 'Iganga'), ('Jinja', 'Jinja'), ('Kaberamaido', 'Kaberamaido'), ('Kaliro', 'Kaliro'), ('Kamuli', 'Kamuli'), ('Kapchorwa', 'Kapchorwa'), ('Katakwi', 'Katakwi'), ('Kibuku', 'Kibuku'), ('Kumi', 'Kumi'), ('Kween', 'Kween'), ('Luuka', 'Luuka'), ('Manafwa', 'Manafwa'), ('Mayuge', 'Mayuge'), ('Mbale', 'Mbale'), ('Namayingo', 'Namayingo'), ('Namisindwa', 'Namisindwa'), ('Namutumba', 'Namutumba'), ('Ngora', 'Ngora'), ('Pallisa', 'Pallisa'), ('Serere', 'Serere'), ('Sironko', 'Sironko'), ('Soroti', 'Soroti'), ('Tororo', 'Tororo')]), ('Northern Region', [('Abim', 'Abim'), ('Adjumani', 'Adjumani'), ('Agago', 'Agago'), ('Alebtong', 'Alebtong'), ('Amolatar', 'Amolatar'), ('Amudat', 'Amudat'), ('Amuru', 'Amuru'), ('Apac', 'Apac'), ('Arua', 'Arua'), ('Dokolo', 'Dokolo'), ('Gulu', 'Gulu'), ('Kaabong', 'Kaabong'), ('Kitgum', 'Kitgum'), ('Koboko', 'Koboko'), ('Kole', 'Kole'), ('Kotido', 'Kotido'), ('Kwania', 'Kwania'), ('Lamwo', 'Lamwo'), ('Lira', 'Lira'), ('Madi-Okollo', 'Madi-Okollo'), ('Maracha', 'Maracha'), ('Moroto', 'Moroto'), ('Moyo', 'Moyo'), ('Nakapiripirit', 'Nakapiripirit'), ('Napak', 'Napak'), ('Nebbi', 'Nebbi'), ('Nwoya', 'Nwoya'), ('Obongi', 'Obongi'), ('Omoro', 'Omoro'), ('Otuke', 'Otuke'), ('Oyam', 'Oyam'), ('Pader', 'Pader'), ('Pakwach', 'Pakwach'), ('Terego', 'Terego'), ('Yumbe', 'Yumbe'), ('Zombo', 'Zombo')]), ('Western Region', [('Buhweju', 'Buhweju'), ('Buliisa', 'Buliisa'), ('Bundibugyo', 'Bundibugyo'), ('Bushenyi', 'Bushenyi'), ('Hoima', 'Hoima'), ('Ibanda', 'Ibanda'), ('Isingiro', 'Isingiro'), ('Kabale', 'Kabale'), ('Kabarole', 'Kabarole'), ('Kagadi', 'Kagadi'), ('Kakumiro', 'Kakumiro'), ('Kamwenge', 'Kamwenge'), ('Kanungu', 'Kanungu'), ('Kasese', 'Kasese'), ('Kibaale', 'Kibaale'), ('Kikuube', 'Kikuube'), ('Kiruhura', 'Kiruhura'), ('Kiryandongo', 'Kiryandongo'), ('Kisoro', 'Kisoro'), ('Kitagwenda', 'Kitagwenda'), ('Kyegegwa', 'Kyegegwa'), ('Kyenjojo', 'Kyenjojo'), ('Masindi', 'Masindi'), ('Mbarara', 'Mbarara'), ('Mitooma', 'Mitooma'), ('Ntoroko', 'Ntoroko'), ('Ntungamo', 'Ntungamo'), ('Rubanda', 'Rubanda'), ('Rubirizi', 'Rubirizi'), ('Rukiga', 'Rukiga'), ('Rukungiri', 'Rukungiri'), ('Rwampara', 'Rwampara'), ('Sheema', 'Sheema')])], max_length=100),
        ),
    ]
