# Generated by Django 5.2.11 on 2026-06-16 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle / Boda-Boda'), ('pickup', 'Pickup Truck'), ('lorry', 'Lorry / Truck'), ('van', 'Van / Mini-Bus'), ('tractor', 'Tractor')], max_length=20)),
                ('vehicle_registration', models.CharField(blank=True, help_text='Number plate e.g. UAA 123B', max_length=20)),
                ('capacity_kg', models.DecimalField(decimal_places=2, help_text='Maximum load capacity in kg', max_digits=8)),
                ('coverage_districts', models.TextField(help_text='Comma-separated districts covered e.g. Kampala,Wakiso,Mukono')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_image', models.ImageField(blank=True, help_text='National ID or passport scan', null=True, upload_to='verifications/ids/')),
                ('farm_or_business_photo', models.ImageField(blank=True, help_text='Photo of farm, business premises, or vehicle', null=True, upload_to='verifications/farms/')),
                ('business_reg_number', models.CharField(blank=True, help_text='Business registration number (if applicable)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional context from the applicant')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to user)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
