# Generated by Django 5.2.11 on 2026-07-16 13:40

from django.db import migrations, models
import json


def convert_specialization_to_json(apps, schema_editor):
    """
    Convert existing plain-text specialization values to JSON arrays
    so the migration to JSONField doesn't fail with CHECK constraint.
    """
    # We use raw SQL to avoid the model-level validation
    db = schema_editor.connection
    with db.cursor() as cursor:
        # Get all rows with a specialization value
        cursor.execute("SELECT id, specialization FROM accounts_user WHERE specialization IS NOT NULL AND specialization != ''")
        rows = cursor.fetchall()
        for user_id, spec in rows:
            # If already valid JSON, skip
            try:
                parsed = json.loads(spec)
                if isinstance(parsed, list):
                    continue  # Already a list
                # It's a JSON scalar — wrap it
                new_val = json.dumps([parsed])
            except (json.JSONDecodeError, TypeError):
                # It's a plain string — convert to list
                new_val = json.dumps([spec] if spec else [])
            cursor.execute(
                "UPDATE accounts_user SET specialization = ? WHERE id = ?",
                [new_val, user_id]
            )
        # Also clear empty string values to empty list JSON
        cursor.execute(
            "UPDATE accounts_user SET specialization = '[]' WHERE specialization = '' OR specialization IS NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_transporterprofile_verificationrequest'),
    ]

    operations = [
        # Step 1: Convert existing text values to JSON-valid strings in place
        migrations.RunPython(convert_specialization_to_json, migrations.RunPython.noop),
        # Step 2: Alter the column type
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.JSONField(blank=True, default=list, help_text='List of farming specializations'),
        ),
    ]
