# Generated by Django 5.2.11 on 2026-02-08 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizers', 'Fertilizers'), ('pesticides', 'Pesticides'), ('herbicides', 'Herbicides'), ('tools', 'Tools & Equipment'), ('irrigation', 'Irrigation Equipment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='input_categories/')),
            ],
            options={
                'verbose_name': 'Input Category',
                'verbose_name_plural': 'Input Categories',
            },
        ),
        migrations.CreateModel(
            name='AgriculturalInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.IntegerField()),
                ('unit', models.CharField(help_text='e.g., kg, liters, pieces', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('usage_instructions', models.TextField(blank=True)),
                ('safety_warnings', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='inputs/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='inputs/')),
                ('min_group_order', models.IntegerField(default=1, help_text='Minimum quantity for group purchase discount')),
                ('group_discount_percentage', models.IntegerField(default=0, help_text='Discount % for group orders')),
                ('status', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(limit_choices_to={'user_type': 'input_supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.inputcategory')),
            ],
            options={
                'verbose_name': 'Agricultural Input',
                'verbose_name_plural': 'Agricultural Inputs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupBuyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity', models.IntegerField(help_text='Target quantity to unlock discount')),
                ('current_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open for Joining'), ('closed', 'Target Reached'), ('completed', 'Order Placed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('deadline', models.DateTimeField(help_text='Deadline to reach target')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.agriculturalinput')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_pools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Buy Pool',
                'verbose_name_plural': 'Group Buy Pools',
            },
        ),
        migrations.CreateModel(
            name='GroupBuyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='inputs.groupbuypool')),
            ],
            options={
                'verbose_name': 'Group Buy Participant',
                'verbose_name_plural': 'Group Buy Participants',
                'unique_together': {('pool', 'farmer')},
            },
        ),
    ]
