# Generated by Django 5.2.11 on 2026-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PestAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=200)),
                ('affected_crops', models.CharField(help_text='Comma-separated crops', max_length=300)),
                ('affected_regions', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='How to identify the pest/disease')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('control_measures', models.TextField(help_text='How to control/prevent')),
                ('recommended_products', models.TextField(blank=True, help_text='Recommended pesticides')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pests/')),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pest Alert',
                'verbose_name_plural': 'Pest Alerts',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='PlantingSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('best_planting_start', models.DateField()),
                ('best_planting_end', models.DateField()),
                ('expected_harvest_start', models.DateField()),
                ('expected_harvest_end', models.DateField()),
                ('rainfall_required', models.CharField(help_text='e.g., 800-1200mm', max_length=100)),
                ('temperature_range', models.CharField(help_text='e.g., 20-30°C', max_length=100)),
                ('planting_tips', models.TextField()),
            ],
            options={
                'verbose_name': 'Planting Season',
                'verbose_name_plural': 'Planting Seasons',
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('rain', 'Heavy Rain'), ('drought', 'Drought Warning'), ('storm', 'Storm Warning'), ('frost', 'Frost Warning'), ('heatwave', 'Heatwave')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('affected_regions', models.CharField(help_text='Comma-separated regions', max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('recommendations', models.TextField(help_text='What farmers should do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Weather Alert',
                'verbose_name_plural': 'Weather Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
