# Generated by Django 5.2.11 on 2026-06-16 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_district', models.CharField(help_text='District where goods will be picked up', max_length=100)),
                ('delivery_district', models.CharField(help_text='District where goods will be delivered', max_length=100)),
                ('pickup_address', models.TextField(blank=True, help_text='Specific pickup location / landmark')),
                ('offered_price', models.DecimalField(decimal_places=2, help_text='Transport fee offered in UGX', max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open — Looking for Transporter'), ('assigned', 'Assigned to Transporter'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special delivery instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(help_text='Order this delivery is for', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_request', to='orders.order')),
                ('transporter', models.ForeignKey(blank=True, help_text='Assigned transporter (blank = open request)', limit_choices_to={'user_type': 'transporter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Request',
                'verbose_name_plural': 'Delivery Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
