# Generated by Django 5.2.11 on 2026-07-12 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
        ('marketplace', '0012_alter_product_farmer'),
        ('orders', '0002_deliveryrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='input_product',
            field=models.ForeignKey(blank=True, help_text='Agricultural Input being ordered', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inputs.agriculturalinput'),
        ),
        migrations.AlterField(
            model_name='order',
            name='farmer',
            field=models.ForeignKey(help_text='Farmer or Supplier who will fulfill the order', limit_choices_to={'user_type__in': ['farmer', 'input_supplier']}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product being ordered', null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.product'),
        ),
    ]
