# Generated by Django 5.2.11 on 2026-07-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_total_amount_alter_orderitem_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancelling the order', null=True),
        ),
    ]
