# Generated by Django 5.2.11 on 2026-07-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('news', 'News'), ('product', 'Product'), ('weather', 'Weather'), ('system', 'System'), ('admin', 'Admin'), ('order', 'Order'), ('chat', 'Chat / Negotiation')], max_length=20),
        ),
    ]
